# Uncomment the next line to define a global platform for your project

platform :ios, '16.0'

target 'YARCH-HomeWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'YARCH-HomeWorkTests' do
    pod 'Nimble'
    pod 'Quick', '5.0.1'
  end

  # Pods for YARCH-HomeWork
  pod 'University/UniversityList', path: 'Frameworks/University'
  pod 'SnapKit'
end
