# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPodsHomework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodsHomework
  pod 'UIBasics', path: 'Frameworks/UIBasics'
  pod 'CustomFrameworks/ViewControllers', :git => 'git@www.gitlab-alfa-campus.ru:iagolubev/homework-cocoapods.git', :branch => 'homework7'
  pod 'CustomFrameworks/Views', :git => 'git@www.gitlab-alfa-campus.ru:iagolubev/homework-cocoapods.git', :branch => 'homework7'
  pod 'SnapKit', '4.2'
end
